linux_test_task:
  container:
    image: flipstone/stack:v6-2.7.3
    cpu: 6
    memory: 6G
  stack_cache:
    # Note how this is so wildly different than other platforms..
    folder: /stack-root
  install_script:
    - apt update
    - apt install bmake
    - bmake setup
  test_script:
    - bmake

freebsd_test_task:
  freebsd_instance:
    image_family: freebsd-13-0
    cpu: 6
    memory: 6G
  stack_cache:
    folder: ~/.stack
  install_script:
    - pkg install -y hs-stack
    - make setup
  test_script:
    - make

macos_test_task:
  macos_instance:
    image: monterey-base
    cpu: 6
    memory: 6G
  stack_cache:
    folder: ~/.stack
  install_script:
    - brew install haskell-stack bmake
    - bmake setup
  test_script:
    - bmake
