name: non-empty-text
version: 0.2.0
category: Data, Text, NonEmpty
synopsis: Non empty Data.Text type
description: |
  Typesafe thin wrapper around Data.Text to make impossible to be empty (to
  always hold at least on character)
author: Antoine Catton, Trevis Elser
maintainer: Trevis Elser <trevis@flipstone.com>
github: flipstone/haskell-non-empty-text
license: MIT
tested-with: GHC == 8.8.4, GHC == 8.10.7

flags:
  ci:
    description: More strict ghc options used for development and ci, not intended for end-use.
    manual: true
    default: false

dependencies:
  - base >=4.8 && <5
  - deepseq >=1.3.0.0 && <1.5
  - text >=1.2 && <3

extra-source-files:
  - CHANGELOG.md

library:
  source-dirs: src
  exposed-modules:
    - Data.NonEmptyText

  when:
    - condition: flag(ci)
      then:
        ghc-options:
          - -Wall
          - -Werror
          - -Wcompat
          - -Widentities
          - -Wincomplete-uni-patterns
          - -Wincomplete-patterns
          - -Wincomplete-record-updates
          - -Wmissing-local-signatures
          - -Wmissing-export-lists
          - -Wmissing-import-lists
          - -Wnoncanonical-monad-instances
          - -Wredundant-constraints
          - -Wpartial-fields
          - -Wmissed-specialisations
          - -Wno-implicit-prelude
          - -Wno-safe
          - -Wno-unsafe
      else:
        ghc-options:
          - -Wall
          - -fwarn-incomplete-uni-patterns
          - -fwarn-incomplete-record-updates


tests:
  spec:
    main: Spec.hs
    source-dirs: test
    other-modules:
      - Data.NonEmptyTextSpec
    dependencies:
      - non-empty-text
      - hspec
      - QuickCheck >=2.10 && <3
  doctest:
    main: DocTest.hs
    source-dirs: .
    dependencies:
      - doctest
      - Glob
